//! End-to-end integration test — drives the actual binary through the
//! full pipeline and verifies every artifact + evidence file lands.

use std::path::{Path, PathBuf};
use std::process::Command;

use tempfile::TempDir;

/// Absolute path of the binary cargo just built for this test.
fn bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_super-dev"))
}

fn run(args: &[&str], cwd: &Path) {
    let status = Command::new(bin())
        .args(args)
        .current_dir(cwd)
        .status()
        .expect("super-dev binary should be invocable");
    assert!(status.success(), "super-dev {:?} failed: {status}", args);
}

#[test]
fn full_pipeline_offline_end_to_end() {
    let tmp = TempDir::new().unwrap();
    let root = tmp.path();

    // Step 1 — run: research → docs → pause at docs_confirm.
    // No --backend / --api → offline deterministic templates (default).
    run(
        &[
            "run",
            "build a commercial-grade login system",
            "--slug",
            "demo",
        ],
        root,
    );

    for rel in [
        "output/demo-research.md",
        "output/demo-prd.md",
        "output/demo-architecture.md",
        "output/demo-uiux.md",
        "output/knowledge-cache/demo-knowledge-bundle.json",
        ".super-dev/workflow-state.json",
        ".super-dev/audit/tool-calls.jsonl",
    ] {
        assert!(root.join(rel).is_file(), "missing artifact: {rel}");
    }

    // Step 2 — continue: spec → frontend → pause at preview_confirm
    run(&["continue"], root);
    assert!(root.join("output/demo-execution-plan.md").is_file());
    assert!(root.join("output/demo-frontend-notes.md").is_file());

    // Step 3 — continue: backend → quality → delivery → done
    run(&["continue"], root);
    assert!(root.join("output/demo-backend-notes.md").is_file());
    assert!(root.join("output/demo-quality-gate.json").is_file());
    assert!(root.join("output/demo-quality-gate.md").is_file());
    assert!(root.join("output/demo-compliance-mapping.json").is_file());

    // Proof pack zip lands in release/
    let release = root.join("release");
    let entries: Vec<_> = std::fs::read_dir(&release)
        .unwrap()
        .filter_map(Result::ok)
        .collect();
    assert!(
        entries
            .iter()
            .any(|e| e.path().extension().and_then(|s| s.to_str()) == Some("zip")),
        "no proof-pack zip in release/"
    );

    // Step 4 — verify reports a coherent final state
    let verify_out = Command::new(bin())
        .args(["verify"])
        .current_dir(root)
        .output()
        .expect("verify should run");
    assert!(verify_out.status.success());
    let stdout = String::from_utf8_lossy(&verify_out.stdout);
    assert!(stdout.contains("phase=delivery"));
    assert!(stdout.contains("SUPER_DEV_HOST_SPEC_V1"));
    assert!(stdout.contains("tool-calls.jsonl"));

    // Step 5 — report regenerates the compliance mapping
    run(&["report"], root);
}

#[test]
#[cfg(unix)]
fn run_with_backend_drives_a_fake_host_cli() {
    use std::os::unix::fs::PermissionsExt;

    let tmp = TempDir::new().unwrap();
    let root = tmp.path();

    // A fake `claude` binary: ignores its args, prints a known PRD-shaped
    // markdown body to stdout. This proves `--backend claude-code` routes
    // the coach prompt through a subprocess and captures its output.
    let fake = root.join("fake-claude");
    std::fs::write(
        &fake,
        "#!/bin/sh\necho '# Generated by fake host CLI'\necho '## Goal'\necho 'driven via --backend'\n",
    )
    .unwrap();
    let mut perms = std::fs::metadata(&fake).unwrap().permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&fake, perms).unwrap();

    let status = Command::new(bin())
        .args([
            "run",
            "build a login page",
            "--slug",
            "demo",
            "--backend",
            "claude-code",
        ])
        .current_dir(root)
        .env("SUPER_DEV_CLAUDE_BIN", &fake)
        .status()
        .expect("super-dev run --backend should be invocable");
    assert!(status.success(), "run --backend failed: {status}");

    // The research artifact should carry the fake host's output verbatim.
    let research = std::fs::read_to_string(root.join("output/demo-research.md")).unwrap();
    assert!(
        research.contains("Generated by fake host CLI"),
        "research artifact was not produced by the backend: {research}"
    );
}

#[test]
fn spec_clauses_subcommand_lists_every_clause() {
    let out = Command::new(bin())
        .args(["spec", "--clauses"])
        .output()
        .expect("spec --clauses should run");
    assert!(out.status.success());
    let stdout = String::from_utf8_lossy(&out.stdout);
    for id in [
        "SD-CODE-001",
        "SD-CODE-002",
        "SD-CODE-003",
        "SD-CODE-004",
        "SD-FLOW-001",
        "SD-FLOW-006",
        "SD-ART-002",
        "SD-EVID-001",
        "SD-EVID-005",
        "SD-META-001",
    ] {
        assert!(stdout.contains(id), "spec --clauses missing {id}");
    }
    assert!(stdout.contains("Phase chain:"));
}

// `super-dev hook` was removed in 4.2 along with the injection-style
// plugin architecture. The governance rules it exposed (check_emoji,
// check_color_tokens, …) are still tested at the unit level in
// `super-dev-governance`; the CLI surface for them is gone because no
// host-side hooks remain to invoke it.

#[test]
fn examples_command_prints_cheatsheet() {
    let out = Command::new(bin())
        .args(["examples"])
        .output()
        .expect("examples should run");
    assert!(out.status.success());
    let s = String::from_utf8_lossy(&out.stdout);
    // Spot-check the main entrypoints + new 4.4 surface.
    assert!(s.contains("super-dev"));
    assert!(s.contains("super-dev run"));
    assert!(s.contains("super-dev continue"));
    // 4.4 cheat-sheet headings:
    assert!(s.contains("First-time use"));
    assert!(s.contains("slash commands") || s.contains("Inside the TUI"));
    assert!(s.contains("/claude"));
    assert!(s.contains("Shift+Enter"));
}

#[test]
fn guide_command_prints_walkthrough() {
    let out = Command::new(bin())
        .args(["guide"])
        .output()
        .expect("guide should run");
    assert!(out.status.success());
    let s = String::from_utf8_lossy(&out.stdout);
    assert!(s.contains("60-second walkthrough"));
    assert!(s.contains("THE COMMAND SURFACE"));
    assert!(s.contains("docs_confirm"));
    assert!(s.contains("preview_confirm"));
    assert!(s.contains("INPUT BOX FEATURES"));
}

#[test]
fn run_help_includes_examples() {
    let out = Command::new(bin())
        .args(["run", "--help"])
        .output()
        .expect("run --help should run");
    assert!(out.status.success());
    let s = String::from_utf8_lossy(&out.stdout);
    assert!(s.contains("EXAMPLES:"));
    assert!(s.contains("super-dev run"));
    assert!(s.contains("--backend claude-code"));
}

#[test]
fn unknown_subcommand_suggests_a_correction() {
    // clap's typo / "did you mean" suggestion is on by default.
    let out = Command::new(bin())
        .args(["rin"]) // "rin" → run
        .output()
        .expect("unknown command should run");
    assert!(!out.status.success());
    let s = String::from_utf8_lossy(&out.stderr);
    // clap prints either "did you mean" or a similar suggestion line.
    let lower = s.to_lowercase();
    assert!(
        lower.contains("did you mean") || lower.contains("similar") || lower.contains("'run'"),
        "expected a did-you-mean hint, got:\n{s}"
    );
}
